### ISSUE TITLE
OAuth 2.0 Authentication Flow?

### ISSUE THREAD

**Issue by victorhooi** [krishamoud/meteor-linkedin-api#1]
Sorry if I've missed something obvious, but I can't seem to see how to use this package with a OAuth 2.0 flow - e.g. requesting permissions from a user, doing the redirect, and then say, querying their profile.

Is that possible at the moment?

**Comment by krishamoud** [comment]
That is not currently possible with this version.  I can add login features in the future but I used https://github.com/yefim/meteor-accounts-linkedin to handle the OAuth flow.

**Comment by victorhooi** [comment]
Hmm, I had a look at https://github.com/yefim/meteor-linkedin and https://github.com/yefim/meteor-accounts-linkedin, and it wasn't really clear that you could do the above (i.e. request permissions for a user, do the redirect, and then query their profile).

Yeah,login feature would be awesome =). Are you still actively working on this package much? (It seems to be the only Meteor LinkedIn API package I could find).

**Comment by krishamoud** [comment]
I haven't added any code to this repo in a while but I could probably hammer out a login feature this weekend.

**Comment by victorhooi** [comment]
That would be pretty awesome, actually.

Good luck!

**Comment by Nullpo** [comment]
+1 !

**Comment by krishamoud** [comment]
Hey sorry to get back so late.  I finally had time to do this but I did it as a separate package instead.  You can use https://github.com/krishamoud/meteor-accounts-linkedin which will work with this package.
